### ISSUE TITLE
Issues with the Get Focus button

### ISSUE THREAD

**Issue by 1105420698** [chen-yaoyu/think#1]
the button background is just a background, and users will feel awkward if they can only press the text in the "button"  to get focused.

**Comment by chen-yaoyu** [comment]
Good point. I'll address this in the design documents (to be published.)

**Comment by 1105420698** [comment]
Assign that to me, I can fix it.

**Comment by chen-yaoyu** [comment]
Cool just submit a pull! I’ll also be releasing the design doc tonight.

**Comment by runkaiz** [comment]
This is  #fixed in #14
